# Data PVC
{{ if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "n8n.fullname" . }}-data"
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
  {{- with .Values.persistence.data.annotations }}
    annotations:
      {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.persistence.data.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
  {{- if .Values.persistence.data.storageClass }}
  storageClassName: {{ .Values.persistence.data.storageClass }}
  {{- end }}
{{ end }}
---
# Files PVC
{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "n8n.fullname" . }}-files"
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
  {{- with .Values.persistence.files.annotations }}
    annotations:
      {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.persistence.files.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.files.size }}
  {{- if .Values.persistence.files.storageClass }}
  storageClassName: {{ .Values.persistence.files.storageClass }}
  {{- end }}
{{ end }}

